# Generated by Django 5.2.4 on 2025-07-20 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('cakeId', models.AutoField(primary_key=True, serialize=False)),
                ('cakeName', models.CharField(max_length=100)),
                ('cakeDescription', models.TextField()),
                ('cakeFlavour', models.CharField(max_length=50)),
                ('cakeImage', models.ImageField(upload_to='cake_images/')),
                ('cakeTags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('cakeIngredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('cakeEggOptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
            ],
        ),
    ]
